name: prep_telogator2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.85
  - bzip2=1.0.8
  - ncbi-datasets-cli=18.9.0
  - numpy=2.3.0
  - pbmm2=1.17.0
  - pysam=0.23.3
  - scipy=1.15.2
  - seqkit=2.12.0
  - seqtk=1.5
  - pip:
      - pandas==2.3.3
      - pyyaml==6.0.3
      - scikit-allel==1.3.13
